#:schema node_modules/wrangler/config-schema.json
name = "nantangin"   # <-- Sudah diganti sesuai ekspektasi Cloudflare
compatibility_date = "2026-05-25"
compatibility_flags = [ "nodejs_compat" ]

# Arahkan ke file format ESM (.js) hasil build baru
main = "server.js"

[assets]
directory = "dist"
binding = "ASSETS"

[browser]
binding = "MY_BROWSER"

[[kv_namespaces]]
binding = "PUSPRESNAS_KV"
id = "375e8df827f44fb2b014e3b08e56e8d6"