#:schema node_modules/wrangler/config-schema.json
name = "nantangin"   # <-- Sudah diganti sesuai ekspektasi Cloudflare
compatibility_date = "2026-05-25"
compatibility_flags = [ "nodejs_compat" ]

# Arahkan ke file format ESM (.js) hasil build baru
main = "dist/server.js"

[assets]
directory = "./dist"
binding = "ASSETS"

[browser]
binding = "MY_BROWSER"